### PR TITLE
[FW][FIX] stock_multi_store: Allow to unarchive records with stores.

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/multi-store#34

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/multi-store/pull/35).

**Comment by fw-bot-adhoc** [comment]
Ping @nicomacr, @jjscarafia
This PR targets 15.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+

**Comment by jjscarafia** [comment]
@fw-bot-adhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Pull request closed without merging**
