### PR TITLE
[MIG] base_multi_store: Migration to 16.0

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/multi-store/pull/48).

**Comment by nicomacr** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/multi-store/pull/48).

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@vib-adhoc @nicomacr I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
