### PR TITLE
[FW][MIG] account_multi_store: Migration to 15.0

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/multi-store#44

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/multi-store/pull/45).

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @jjscarafia this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+

**Comment by fw-bot-adhoc** [comment]
@vib-adhoc @jjscarafia this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by jjscarafia** [comment]
@roboadhoc r+

**Pull request closed without merging**
