### PR TITLE
[MIG] stock_multi_store: Migration to 18.0

### PR DESCRIPTION
**Pull request by matiasperalta1**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/multi-store/pull/60).

**Comment by matiasperalta1** [comment]
@roboadhoc override=ci/runbot-oba

**Comment by roboadhoc** [comment]
I'm sorry, @matiasperalta1: you are not allowed to override this status.

**Comment by rov-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
